# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipg_app.Offer'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipg_app.Operator'),
        ),
    ]
