# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0004_auto_20180511_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloffercode',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offercode',
            name='offer',
        ),
        migrations.AddField(
            model_name='historicalsupplyorder',
            name='offer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipg_app.Offer'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipg_app.Offer'),
        ),
    ]
