# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0006_auto_20180511_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloffercode',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='offercode',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='historicaloffercode',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='offer_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipg_app.OfferCode'),
        ),
        migrations.AddField(
            model_name='offercode',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='offer_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ipg_app.OfferCode'),
        ),
    ]
