# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0008_auto_20180511_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='offer_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ipg_app.OfferCode'),
        ),
    ]
