# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0010_auto_20180521_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='offer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipg_app.Offer'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ipg_app.Offer'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='offer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipg_app.OfferCode'),
        ),
    ]
