# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0011_auto_20180522_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorder',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='offer',
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='catalog',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipg_app.Catalog'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ipg_app.Catalog'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
