# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0012_auto_20180522_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffer',
            name='image',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
