# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipg_app', '0013_auto_20180522_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseOrderLine',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('offerId', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('productId', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operator', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipg_app.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'historical purchase order line',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerId', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('productId', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operator', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipg_app.PurchaseOrder')),
            ],
        ),
    ]
