# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0014_historicalpurchaseorderline_purchaseorderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorder',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaseorder',
            name='offer_code',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='offer_code',
        ),
    ]
