# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0015_auto_20180523_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpurchaseorderline',
            old_name='offerId',
            new_name='offer_id',
        ),
        migrations.RenameField(
            model_name='historicalpurchaseorderline',
            old_name='name',
            new_name='offer_name',
        ),
        migrations.RenameField(
            model_name='historicalpurchaseorderline',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='offerId',
            new_name='offer_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='name',
            new_name='offer_name',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='productId',
            new_name='product_id',
        ),
    ]
