# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0016_auto_20180523_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderline',
            name='currency',
            field=models.CharField(default='L', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='currency',
            field=models.CharField(default='L', max_length=3),
            preserve_default=False,
        ),
    ]
