# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0020_auto_20180525_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='operator',
        ),
    ]
