# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0023_auto_20180528_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipg_app.Operator')),
            ],
        ),
    ]
