# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0026_auto_20180529_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='target',
            field=models.CharField(default='', max_length=255),
        ),
    ]
