# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipg_app', '0027_banner_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(),
        ),
    ]
